version: "3"
services:
  database:
    image: "postgres:latest"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: always
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    networks:
    - app-network

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    networks:
    - app-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:password@database:5432/inventory
    depends_on:
      database:
        condition: service_healthy

networks:
  app-network:
    driver: bridge